= LEO IOT

Projekt HTL Leonding, Internet of Things (mehrere Gnerationen)


== Situation

man kennts -> mehrere Stunden in der Schule ->
schlechte luft -> mangelnde Konzentration, etc. ->
keiner denkt dran die fenster aufzumachen

== Wie lösen wir so ein Problem

Sensorboxen in jedem Raum

Warnung (z.B. Ampel) fürs Lüften

== LEO BOX

Co2, Luftfäuchtigkeit, Temperatur, ...

Elektronik Abteilung (Werkstätte)

Schwellenwerte werden auf da Box over the air configuriert

Standalone -> Bauen Backend + Frontend

== Grafische Dastellung

Daten sind nutzlos ohne Darstellung -> Dashboard


== 3D Modell

Live Demo

== Dashboard

* Live Demo
* Zukunft
** Grafana
** Graphen
** Warnungen (Derzeit dummy data)

== System Architektur

* Sensor Boxen (Von uns)
* MQTT Broker (Mosquitto)
* Backend (Quarkus, Optimiert für Cloud/Containerizing)
* TimescaleDB (bassiert auf Postgres, für viele Daten (IOT))
* Frontend (Angular)
* Revers Proxy (Traefik (GO))

== Ziele

Zuerst Regel basiert
z.B. Temperatur sinkt (Fenster offen)

Funkioniert jedoch nur wenns draußen Kälter ist (Winter)

Deswegen AI bassiert das ganze auswerten
