= Development

== Prerequesites

- Node.js
- npm
- Angular CLI

First of all make a quick check on your node and angular versions.
Running
[source, shell script]
----
ng --version
----
should return:
[source, shell script]
----
Angular CLI: [at least 7.0]
Node: [at least 8]
----

Update or install missing versions.

== Clone the repository

[source, shell script]
----
git clone https://github.com/leo-iot/leo-iot-web
----

== Install dependencies

Navigate to the project directory and run

[source, shell script]
----
npm install
----

== Development server

Run
[source, shell script]
----
ng serve
----
for a dev server. Navigate to `http://localhost:4200/`. The app will automatically reload if you change any of the source files.



== Code scaffolding

Run

[source, shell script]
----
ng generate component component-name
----
to generate a new component. You can also use
[source, shell script]
----
ng generate directive|pipe|service|class|guard|interface|enum|module`.
----

== Build

Run
[source, shell script]
----
ng build
----
to build the project. The build artifacts will be stored in the `dist/` directory. Use the `--prod` flag for a production build and `--aot` for ahead of time compilation.

== Running unit tests

Run
[source, shell script]
----
ng test
----
to execute the unit tests via [Karma](https://karma-runner.github.io). The test are configured to run on TravisCI therefore a HeadlessChrome Browser is used as default browser. You can add browsers in the karma config file.

== Running end-to-end tests

Run
[source, shell script]
----
ng e2e
----
to execute the end-to-end tests via [Protractor](http://www.protractortest.org/).
E2e tests are defined in /e2e there are only the default files generated by `ng new`.
