= Getting Started
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left


== Clone Repository

[source, shell]
----
git clone https://github.com/htl-leonding-project/leo-iot
----

== Getting Started Development

=== Server

Please refer to the link:../leo-iot-server/getting-started[getting started] page of the server module.

=== Start Angular in development Mode

Please refer to the link:../leo-iot-web/getting-started[getting started] page of the server module.

== Getting Started Production

=== Build

This command is for building the whole project. It will produce a docker image for every component.

[source,shell]
----
docker-compose build
----

=== Start

This will start the whole application with frontend, backend etc.

[source,shell]
----
docker-compose up -d
----

NOTE: -d option is for daemon. If you don't want to start it in the background, remove this option.
